name: GitHub Actions CI/CD

on: 
  push:
    branches: '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: .NET Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"
      - name: Restore
        run: dotnet restore
        
      - name: Style Check
        run: dotnet format
        
      - name: Debug Build and Static Code Analysis
        run: dotnet build --no-restore /p:RunCodeAnalysis=true --configuration Debug
        
      - name: Release Build and Static Code Analysis
        run: dotnet build --no-restore /p:RunCodeAnalysis=true --configuration Release

      - name: Test
        run: dotnet test --no-build

      - name: Update Documentation
        uses: readthedocs/actions/preview@v1
